### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dvorapa** [Artanidos/FlatSiteBuilderPython#1]
I love the idea, anyway it crashes on almost any occasion. I got into the point of creating first menu item, then it crashed, and after restart it crashes when I click on almost everything. Using fully updated rolling release Arch, so I should be fine

**Comment by Artanidos** [comment]
Oh sry for delay...
Have just seen this issue.
Can you please start the app in a terminal an post the output.
There should be some errors printed.

**Comment by ihph** [comment]
Hello I had the same issue...when launched in terminal it gives the following when trying to add a menu item for instance:

\qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 883, resource id: 11319882, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "widgets/menueditor.py", line 278, in addButtonClicked
NameError: name 'MenuItem' is not defined
Aborted (core dumped)

**Comment by Artanidos** [comment]
Should be fixed with the next release

**Comment by Artanidos** [comment]
Just released a new version.
