### ISSUE TITLE
How to build this on linux?

### ISSUE THREAD

**Issue by tobip** [Artanidos/FlatSiteBuilderPython#2]
Could you provide some more infos on how to build this project on linux?
After figuring out that I have to install pyinstaller manually, I still get these errors:

`5720 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtbase_*.qm. These translations were not packaged.
6363 WARNING: Unable to find Qt5 translations /usr/share/qt/translations/qtdeclarative_*.qm. These translations were not packaged.
Unable to find "/usr/lib/nss/*.so" when adding binary and data files.
mkdir: cannot create directory ‘packages/com.vendor.product/data/plugins’: No such file or directory
mkdir: cannot create directory ‘packages/com.vendor.product/data/themes’: No such file or directory
mkdir: cannot create directory ‘packages/com.vendor.product/data/sources’: No such file or directory
mkdir: cannot create directory ‘packages/com.vendor.product/data/sites’: No such file or directory
cp: cannot stat 'dist/main/*': No such file or directory
cp: target 'packages/com.vendor.product/data/plugins' is not a directory
cp: target 'packages/com.vendor.product/data/themes' is not a directory
mv: cannot stat 'packages/com.vendor.product/data/main': No such file or directory
bash: /home/art/Qt/Tools/QtInstallerFramework/3.1/bin/binarycreator: No such file or directory
`

Using Manjaro Linux.
Thanks for your help, I would love to use this app!

**Comment by Artanidos** [comment]
There will be a release the next days.

**Comment by Artanidos** [comment]
There is a release with an executable.
There is also a script (build.sh) to build a release.
