### ISSUE TITLE
How to install on W10?

### ISSUE THREAD

**Issue by dome68** [Artanidos/FlatSiteBuilderPython#3]
Sorry Artanidos, but I don't understand how to install the software on Windos10.
I have the .Setup file but it doesn't work.
Doesn't exist the .exe file?
Thanks.

**Comment by Artanidos** [comment]
I am just doing a version for Linux and I should be ported to Windows in the next days.
But please be patient because I am on a journey right now.

**Comment by dome68** [comment]
Thanks,
Don't worry, I'll be patient.
Bye.
Domenico

Il giorno lun 2 dic 2019 alle ore 18:20 Olaf Japp <notifications@github.com>
ha scritto:

**Comment by Artanidos** [comment]
Yesterday I have tried to run the app on Windows and guess what. 
It refuses to run.
So I asked myself if I should support Windows at all.
It was a NO.

But there is something interesting:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by dome68** [comment]
Ok, I'll try it in a Virtual Machine on my W10 OS.
